/* Generated by AN DISI Unibo */ 
package it.unibo.robotsnartusage

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Robotsnartusage ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 val StepTime = 345 
			   var NLAP     = 0		
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outblue("$name | starts ")
						 clearlog("./logs/robotsmart26usage.log") //vedi src/main/resources/logback.xml  
						subscribe(  "robotsmart26in_out" ) //mqtt.subscribe(this,topic)
						CommUtils.outblue("$name | subscribed")
						forward("setrobotstate", "setpos(0,0,down)" ,"robotsmart" ) 
						delay(500) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="posrobotbeforeslot", cond=doswitch() )
				}	 
				state("posrobotbeforeslot") { //this:State
					action { //it:State
						 logger.info(  "${currentState.stateName}: setrobotstate at HOME"  )  
						forward("setplanbuildelay", "value(0)" ,"robotsmart" ) 
						request("moverobot", "moverobot(2,5,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t00",targetState="handleSonarWenv",cond=whenEvent("sonaralarm"),interruptedStateTransitions)
					transition(edgeName="t01",targetState="goSlot31",cond=whenReply("moverobotdone"))
					transition(edgeName="t02",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("handleSonarWenv") { //this:State
					action { //it:State
						CommUtils.outgreen("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						returnFromInterrupt(interruptedStateTransitions)
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("goSlot31") { //this:State
					action { //it:State
						CommUtils.outblue("$name | goSlot31 ")
						delay(2000) 
						request("moverobot", "moverobot(3,1,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t03",targetState="handleSonarWenv",cond=whenEvent("sonaralarm"),interruptedStateTransitions)
					transition(edgeName="t04",targetState="backtohome",cond=whenReply("moverobotdone"))
					transition(edgeName="t05",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("backtohome") { //this:State
					action { //it:State
						CommUtils.outblue("$name | backtohome ")
						delay(2000) 
						request("moverobot", "moverobot(0,0,$StepTime)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 interrupthandle(edgeName="t06",targetState="handleSonarWenv",cond=whenEvent("sonaralarm"),interruptedStateTransitions)
					transition(edgeName="t07",targetState="end",cond=whenReply("moverobotdone"))
					transition(edgeName="t08",targetState="end",cond=whenReply("moverobotfailed"))
				}	 
				state("end") { //this:State
					action { //it:State
						request("tuneAtHome", "tuneAtHome(end)" ,"robotsmart" )  
						CommUtils.outmagenta("$name in ${currentState.stateName} | $currentMsg | ${Thread.currentThread().getName()} n=${Thread.activeCount()}")
						 	   
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t09",targetState="bye",cond=whenReply("tuneDone"))
				}	 
				state("bye") { //this:State
					action { //it:State
						delay(1000) 
						CommUtils.outblue("$name | bye ")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
