/* Generated by AN DISI Unibo */ 
package it.unibo.sistemas

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sistemas ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		
				fun eval(x: Double): String{
					val R = 3*x
					return ""+R
				}
			
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | Wello Horld")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleEval",cond=whenDispatch("eval"))
					transition(edgeName="t01",targetState="handleRequest",cond=whenRequest("evalr"))
				}	 
				state("handleEval") { //this:State
					action { //it:State
						 var R = ""  
						if( checkMsgContent( Term.createTerm("arg(V)"), Term.createTerm("arg(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val V = payloadArg(0)  
								CommUtils.outgreen("$name | valuto $V")
								 R = eval(V.toDouble())  
								CommUtils.outred("$name | result = $R")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						 var R = "" 
						if( checkMsgContent( Term.createTerm("argr(V)"), Term.createTerm("argr(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val V = payloadArg(0)  
								CommUtils.outgreen("$name | valutor $V")
								 R = eval(V.toDouble())  
								CommUtils.outred("$name | resultr = $R")
						}
						answer("evalr", "evalreply", "value($R)"   )  
						CommUtils.outblack("$name | handlereply ends")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
