/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
			
				var id = 0
		    	var T_On  = 150L
		       	var T_Off = 1000L 
		       	var bSync = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 
						    		id = name.split('_').last().toInt() 
						
						    		T_Off = (1000..2000).random().toLong() 
						CommUtils.outcyan("$name | ID=$id, T_Off=$T_Off")
						observeResource("localhost","8011","ctxfireflysync","sonar","info")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="spenta", cond=doswitch() )
				}	 
				state("spenta") { //this:State
					action { //it:State
						 if(!bSync) T_Off = (1000..4000).random().toLong()  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_spenta", 
				 	 					  scope, context!!, "local_tout_"+name+"_spenta", T_Off )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="accesa",cond=whenTimeout("local_tout_"+name+"_spenta"))   
					transition(edgeName="t01",targetState="handleinfo",cond=whenDispatch("info"))
				}	 
				state("accesa") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | FLASH!")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_accesa", 
				 	 					  scope, context!!, "local_tout_"+name+"_accesa", T_On )  //OCT2023
					}	 	 
					 transition(edgeName="t12",targetState="spenta",cond=whenTimeout("local_tout_"+name+"_accesa"))   
					transition(edgeName="t13",targetState="handleinfo",cond=whenDispatch("info"))
				}	 
				state("handleinfo") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("changed(SOURCE,TERM)"), Term.createTerm("changed(SOURCE,TERM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								
								                val distance = payloadArg(1).toInt()
								                bSync = (distance < 100)
								                
								                // Se dobbiamo sincronizzarci, usiamo tutti lo stesso tempo di attesa
								                if(bSync) T_Off = 2000L 
								CommUtils.outmagenta("$name | Update Sonar: dist=$distance, bSync=$bSync")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="accesa", cond=doswitchGuarded({ bSync  
					}) )
					transition( edgeName="goto",targetState="spenta", cond=doswitchGuarded({! ( bSync  
					) }) )
				}	 
			}
		}
} 
