/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
			
				var id = name.split('_').last().toInt() 
				var X    = id / 20 //20 è la lunghezza della linea della griglia
		        var Y	 = id % 20
		    	var T_On  = 1000L
		       	var T_Off = 2000L // Periodo base differente per testare la sincronia
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 
						    		id = name.split('_').last().toInt() 
						
						    		T_Off = (1500..3000).random().toLong() 
						CommUtils.outcyan("$name | ID=$id, T_Off=$T_Off")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="spenta", cond=doswitch() )
				}	 
				state("spenta") { //this:State
					action { //it:State
						forward("cellstate", "cellstate($X,$Y,0)" ,"griddisplay" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_spenta", 
				 	 					  scope, context!!, "local_tout_"+name+"_spenta", T_Off )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="accesa",cond=whenTimeout("local_tout_"+name+"_spenta"))   
					transition(edgeName="t01",targetState="handleFlash",cond=whenEvent("flash"))
				}	 
				state("accesa") { //this:State
					action { //it:State
						 emit("flash", "flash($id)")  
						forward("cellstate", "cellstate($X,$Y,1)" ,"griddisplay" ) 
						CommUtils.outyellow("$name | ACCESO")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_accesa", 
				 	 					  scope, context!!, "local_tout_"+name+"_accesa", T_On )  //OCT2023
					}	 	 
					 transition(edgeName="t12",targetState="spenta",cond=whenTimeout("local_tout_"+name+"_accesa"))   
				}	 
				state("handleFlash") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("flash(ID)"), Term.createTerm("flash(ID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 val SenderID = payloadArg(0).toInt()  
								if(  id > 1 && SenderID == 1  
								 ){CommUtils.outmagenta("$name | Sincronizzo con lucciola master")
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="accesa", cond=doswitchGuarded({ id > 1  
					}) )
					transition( edgeName="goto",targetState="spenta", cond=doswitchGuarded({! ( id > 1  
					) }) )
				}	 
			}
		}
} 
