/* Generated by AN DISI Unibo */ 
package it.unibo.mockobserver

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Mockobserver ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var DurataRicevuta = 0L  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | In attesa")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="handleFlash",cond=whenEvent("flash"))
				}	 
				state("handleFlash") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("flash(V,DUR)"), Term.createTerm("flash(V,T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
								                val IdLucciola = payloadArg(0)
								                DurataRicevuta = payloadArg(1).toLong() 
								CommUtils.outyellow("$name | Vedo luce da Lucciola")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_handleFlash", 
				 	 					  scope, context!!, "local_tout_"+name+"_handleFlash", DurataRicevuta )  //OCT2023
					}	 	 
					 transition(edgeName="t13",targetState="fineFlash",cond=whenTimeout("local_tout_"+name+"_handleFlash"))   
				}	 
				state("fineFlash") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | SPenta")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="s0", cond=doswitch() )
				}	 
			}
		}
} 
