/* Generated by AN DISI Unibo */ 
package it.unibo.firefly

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Firefly ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=true ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
			
				var LINELEN = 10		
				val id = name.split('_').last().toInt()		
		        var X    = id % LINELEN
		        var Y	 = id / LINELEN
		    	var T_On  = 0L
		       	var T_Off = 0L
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("name | ($X ; $Y) viva")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="spenta", cond=doswitch() )
				}	 
				state("spenta") { //this:State
					action { //it:State
						
							        T_On  = (600..700).random().toLong() 
							        T_Off = (500..1000).random().toLong()
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_spenta", 
				 	 					  scope, context!!, "local_tout_"+name+"_spenta", T_Off )  //OCT2023
					}	 	 
					 transition(edgeName="t00",targetState="accesa",cond=whenTimeout("local_tout_"+name+"_spenta"))   
				}	 
				state("accesa") { //this:State
					action { //it:State
						forward("flash", "arg($X,$Y,$T_On)" ,"mockobserver" ) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_accesa", 
				 	 					  scope, context!!, "local_tout_"+name+"_accesa", T_On )  //OCT2023
					}	 	 
					 transition(edgeName="t11",targetState="spenta",cond=whenTimeout("local_tout_"+name+"_accesa"))   
				}	 
			}
		}
} 
